architecture:
  name: mlp_3x_216x120x84
  layers:
  - 216
  - 120
  - 84
hyperparameters:
  lr: 0.0003331104514678443
  beta1: 0.919413713793459
  beta2: 0.9232851365807315
  eps: 4.92719357335566e-09
  weight_decay: 7.50108608066958e-06
  dropout: 0.23520569821148946
  leaky_relu_alpha: 0.036080345313143705
seed: 4
best_validation_loss: 0.07838398065567016
best_epoch: 112
terminating_epoch: 128
test_loss: 0.07787153173685074
