architecture:
  name: mlp_3x_192x192x128_do0.25_a0.045
  layers:
  - 192
  - 192
  - 128
  dropout: 0.25
  leaky_relu_alpha: 0.045
hyperparameters:
  lr: 0.001347632520979508
  beta1: 0.9141405520139614
  beta2: 0.9027947009099758
  eps: 4.884443539286252e-09
  weight_decay: 5.11499290635496e-06
seed: 4
best_validation_loss: 0.07704764345884323
best_epoch: 35
terminating_epoch: 70
test_loss: 0.07482371860742569
