architecture:
  name: mlp_3x_256x128x64_do0.1_a0.015
  layers:
  - 256
  - 128
  - 64
  dropout: 0.1
  leaky_relu_alpha: 0.015
hyperparameters:
  lr: 0.001347632520979508
  beta1: 0.9141405520139614
  beta2: 0.9027947009099758
  eps: 4.884443539286252e-09
  weight_decay: 5.11499290635496e-06
seed: 1
best_validation_loss: 0.07850407699346543
best_epoch: 30
terminating_epoch: 65
test_loss: 0.07572325288057327
