architecture:
  name: mlp_3x_256x128x64_do0.1_a0.045
  layers:
  - 256
  - 128
  - 64
  dropout: 0.1
  leaky_relu_alpha: 0.045
hyperparameters:
  lr: 0.003227618399677746
  beta1: 0.8820267109778633
  beta2: 0.9944325424858369
  eps: 5.061536498053407e-07
  weight_decay: 1.325439570460723e-06
seed: 2
best_validation_loss: 0.08237358232736587
best_epoch: 25
terminating_epoch: 60
test_loss: 0.0825656056880951
