architecture:
  name: mlp_2x_192x192_do0.1_a0.015
  layers:
  - 192
  - 192
  dropout: 0.1
  leaky_relu_alpha: 0.015
hyperparameters:
  lr: 0.00011346165063662855
  beta1: 0.9322612848600983
  beta2: 0.9881596521831026
  eps: 3.4561473921402963e-07
  weight_decay: 0.00010498694110461728
seed: 3
best_validation_loss: 0.07257631434202194
best_epoch: 308
terminating_epoch: 324
test_loss: 0.06883601570129394
