architecture:
  layers:
  - 256
  - 128
  dropout: 0.2
  leaky_relu_alpha: 0.015
  name: mlp_2x_256x128_do0.2_a0.015
hyperparameters:
  lr: 2.932248474919265e-05
  beta1: 0.9686407231712125
  beta2: 0.9763010844357638
  eps: 5.823808382847424e-09
  weight_decay: 9.588272061157046e-05
seed: 1
best_validation_loss: 0.07076344426870346
best_epoch: 1000
terminating_epoch: 1000
test_loss: null
