architecture:
  name: mlp_2x_256x128_do0.3_a0.045
  layers:
  - 256
  - 128
  dropout: 0.3
  leaky_relu_alpha: 0.045
hyperparameters:
  lr: 0.00011346165063662855
  beta1: 0.9322612848600983
  beta2: 0.9881596521831026
  eps: 3.4561473921402963e-07
  weight_decay: 0.00010498694110461728
seed: 2
best_validation_loss: 0.068802481675148
best_epoch: 392
terminating_epoch: 420
test_loss: 0.06570959575176238
