architecture:
  name: mlp_3x_192x192x128_do0.15_a0.015
  layers:
  - 192
  - 192
  - 128
  dropout: 0.15
  leaky_relu_alpha: 0.015
hyperparameters:
  lr: 7.721262776682894e-05
  beta1: 0.9678442765183735
  beta2: 0.9672440411913269
  eps: 1.7770613175693132e-09
  weight_decay: 1.1661717603204465e-06
seed: 1
best_validation_loss: 0.07707759410142899
best_epoch: 332
terminating_epoch: 360
test_loss: 0.07752783383131027
