adamw:
  lr:
    min: 1.0e-05
    max: 3.0e-02
    scale: log
  beta1:
    min: 0.85
    max: 0.99
    scale: uniform
  beta2:
    min: 0.9
    max: 0.9999
    scale: uniform
  eps:
    min: 1.0e-09
    max: 1.0e-06
    scale: log
  weight_decay:
    min: 1.0e-06
    max: 1.0e-02
    scale: log

model:
  dropout:
    min: 0.01
    max: 0.5
    scale: uniform
  leaky_relu_alpha:
    min: 0.01
    max: 0.1
    scale: uniform
